### PR TITLE
add force download

### PR DESCRIPTION
**Pull request by anggazan**
hi...i'm Angga from Indonesia, first i'm sorry for my bad english..i'm very helpful with this library but i need some request for this library :
- please add fuction to force download update like forceDownload(true/false) if it's true dialogbox only show "update" button without "remind later" and "ignore".
- please make upgradeNow() function as public so developer can make "force update" button to force download and install uploaded APK file

### CODE REVIEW

**Comment by winsontan520** [comment]
@anggazan I no longer maintain this project. It would be good if you can host the project with your account. I can put a link to your project.

**Comment by anggazan** [comment]
@winsontan520 i'm new in android development and don't know how to do that...maybe @revanmj can do my request...

**Comment by revanmj** [comment]
I just added option to force update check by calling `checkVersion(true)` to my fork (it will simply ignore remind timer). 

I don't think that forcing a user to update (by simply disabling all buttons except Update) or downloading APK file before checking first if it's newer than what already is installed is a good UX, so if you want those options, I propose you create your own fork and add them.

Though I may add more complex solution for the first one in the future (checking additional field in JSON file if app functionality should be blocked until it is updated to most recent version, displaying proper message about it to user and exposing this data to a dev via some listener, so he/she can do actual blocking) as I see how this can be a problem if server side interface is changed without ensuring backwards compatibility.

**Comment by anggazan** [comment]
"checking additional field in JSON file if app functionality should be blocked until it is updated to most recent version"
Yes...that's what i mean of "force update" with disabled "remind later" and "ignore" button so user should update to recent version otherwise app will not work properly because i updated server side script.

**Comment by revanmj** [comment]
In case you still need it, I added this to my fork in 1.7 version.

**Comment by winsontan520** [comment]
Thanks for the contribution, but I no longer maintain this repo. Any PR can go to @revanmj fork https://github.com/revanmj/Android-WVersionManager

**Pull request closed without merging**
